### ISSUE TITLE
Unable to convert

### ISSUE THREAD

**Issue by Cymmerii** [elizabethcd/FurnitureConverter#3]
I'm having an issue in converting on the final step of your guide. I'm using Anaconda and PowerShell, the same one I converted my portraits with. When I enter any variation of `python furniture_converter.py --modName WizardFurniture` I receive this error.
![image](https://user-images.githubusercontent.com/118668585/202902850-3a05451f-e62e-4972-a52a-2d285f90d96e.png)

I've attempted it with just the modname and several of the other arguments, all reproducing the same error. When I add --fileName to it as in the example picture provided I get an unrecognized argument error. I've also tried just using 'py' instead of 'python' as I had to do it that way for my portraits for some reason, but i still get the error.

Any insight on what could be wrong here?
Thank you!

**Comment by elizabethcd** [comment]
Link me to the pack? It kind of looks like there’s a nonstandard character in the pack. Have you tried other packs?

**Comment by Cymmerii** [comment]
https://blog.naver.com/ssm4031/221608130600
I tried going into the files, pics and manifest and translated all of the Korean to English, but it still through the same error. I'm uncertain if thats due to me missing some or if something else is causing it

**Comment by elizabethcd** [comment]
I believe this was fixed in https://github.com/elizabethcd/FurnitureConverter/commit/828efed03cede6f2d7730b1403a742430f654dc2
