### ISSUE TITLE
no furniture in content

### ISSUE THREAD

**Issue by kennakin** [elizabethcd/FurnitureConverter#6]
![nofurn](https://github.com/elizabethcd/FurnitureConverter/assets/164547926/e62e03f0-333e-42d2-9d0a-4100ee019ab7)

if i dont use the name "original" as modNAME i get " No such file or directory: 'original\\manifest.json'"

every time i try to convert it, says no furniture- skipping and creates the new files with no furniture making it a useless nothing in it "mod file" but when i open the original json file, i dont see any issues with it and has the list of furniture plus an extra file with the pictures, i tried powershell but i get "python was not found; run without arguments to install from the microsoft store, or disable this shortcut from settings > manage app execution aliases."

ive followed the steps one by one for hours and i dont understand what is going wrong

**Comment by elizabethcd** [comment]
I'm not sure what exactly is going wrong here, but if you come to the Stardew Valley Discord I can try to help you debug—this doesn't look like something that I can figure out just from looking at what's in the screenshot here but it's probably some kind of formatting issue.
